### ISSUE TITLE
Not working in El Capitain GM

### ISSUE THREAD

**Issue by ftirej** [ultimate-deej/Sculpt-Comfort-Mission-Control#5] opened 2015-09-14 21:22 UTC
When i swipe or press the button nothing happen.

This is the log when i swipe up and down:

-1 43
43 1
-1 43
227 1
224 1
-1 0
43 0
-1 0
227 0
224 0

-1 42
42 1
-1 42
227 1
224 1
-1 0
42 0
-1 0
227 0
224 0

And this is the log when i press the button

227 1
227 0

**Comment by gblmarquez** [comment] 2015-10-10 15:54
Same here, what we can do?

**Comment by ultimate-deej** [comment] 2015-10-11 13:33
Sorry for my late reply.
A possible reason can be updated Dock binary. At the moment I'm not able to test it on El Capitan.

**Comment by mtunad** [comment] 2015-12-24 11:03
Any update?

**Comment by ultimate-deej** [comment] 2015-12-24 22:02
Unfortunately no, I haven't updated yet.

**Comment by clickonchris** [comment] 2015-12-31 19:07
:+1:

**Comment by clickonchris** [comment] 2016-01-01 18:35
I'm not a OS X app developer but I cloned your code and tried to run it on my El Capitan machine.

console keeps outputting the following message:

```
(lldb) attach Dock
error: attach failed: cannot attach to process due to System Integrity Protection
```

**Comment by ultimate-deej** [comment] 2016-01-01 18:58
Can you try to run the app with SIP disabled?

**Comment by clickonchris** [comment] 2016-01-04 02:44
I disabled SIP by following the instructions at http://apple.stackexchange.com/a/208481

After SIP was disabled I was able to start the app just fine.  button click works as expected.  I never used swipe up/down before today so I can't say if it works the same or not.

Obviously disabling SIP is not a great solution.  There's got to be a way to get this app to play nice with SIP, right?

**Comment by ultimate-deej** [comment] 2016-01-04 13:04
A partial solution could be to disable only the debug part of SIP: `csrutil enable --without debug`

**Comment by ultimate-deej** [comment] 2016-01-16 14:03
Ok the issue is kinda resolved so I'm closing it.

**Closed as completed by ultimate-deej** 2016-01-16 14:03 UTC
