### ISSUE TITLE
Run `Sculpt Comfort Mission Control.app` but came with a warning

### ISSUE THREAD

**Issue by Vince-Chen** [ultimate-deej/Sculpt-Comfort-Mission-Control#19] opened 2018-09-28 01:01 UTC
While running `Sculpt Comfort Mission Control.app`, the app popped out a window says "“Sculpt-Comfort-Mission-Control-2.x/Sculpt Comfort Mission Control.app/Contents/Dock Plugin/Dock Plugin.bundle” doesn’t understand the “<<event SCMCinjt>>” message."

By the way, this problem happened after I updated to the mac OS Mojave 10.14.

Expecting your reply!
Thank a lot ^_^

**Comment by ultimate-deej** [comment] 2018-09-28 07:42
I'm still running High Sierra, so I can't do the testing yet. As soon as I update to Mojave, I'll get down to the problem. However, this time I'll try to do it as soon as possible, so that you won't have to wait for me for months 😅.

**Comment by ghost** [comment] 2018-09-29 06:33
I've been enjoying your app a lot! However, since the update to Mojave, I am also experiencing issues with the app. Probably the same issue as Vince-Chen, getting the error that Dock Plugin.bundle doesn't understand the <<event SCMCinjt>> message.
<img width="543" alt="screenshot 2018-09-29 at 15 32 49" src="https://user-images.githubusercontent.com/39552254/46241974-f1c20780-c3fc-11e8-88d5-402347769a0e.png">

Thank you for the great work, your app is a real life saver.

**Comment by ultimate-deej** [comment] 2018-09-29 10:18
@Pimchi Thank you for your kind words!
And for the screenshot too, the problem is more clear now.

**Comment by ultimate-deej** [comment] 2018-10-13 10:31
@Vince-Chen @Pimchi Just checked the app on a clean Mojave install, and it works. Try reinstalling SCMC.

**Comment by Vince-Chen** [comment] 2018-10-14 13:24
@ultimate-deej I did what you said and it works at the first time. But after I enabled SIP, the screenshot that Pimchi provided showed again, and the app still can't work...

**Comment by ultimate-deej** [comment] 2018-10-14 13:36
@Vince-Chen Thanks for the feedback, I'll have another look at it.

**Comment by ultimate-deej** [comment] 2018-10-20 21:40
Alright I was able to reproduce the problem. Haven't resolved it yet though. Stay tuned.

**Comment by ultimate-deej** [comment] 2018-10-23 15:38
What I found is that disabling SIP is currently the only option.
See related:
https://github.com/w0lfschild/cDock2/issues/131
https://totalfinder.binaryage.com/sip

As I can't do anything at the moment, I'm closing the issue.

**Closed as completed by ultimate-deej** 2018-10-23 15:38 UTC
